@startuml
|Пользователь|
start

repeat

:Выбор функции
1 - Просмотр списка смартфонов по убыванию 
(по сочетанию свойств «модель» и «размер диагонали экрана») 
с возможностью экспорта данных
2 - Заполнить список смартфонов (все текущие данные из списка сотрутся)
3 - Выход из программы;

|Работа со списком смартфонов|
switch (Выбор пользователя)
case (1)
    :Показать список смартфонов;
    :Если список пуст, отобразить сообщение;
case (2)
    :Ввести размер списка смартфонов;

    repeat
        :Ввод модели смартфона;

       repeat
            :Ввод цены смартфона;
            if (Цена корректна?) then (Да)
                
            else (Нет)
                :Вывести сообщение об ошибке;
            endif
        repeat while (Цена корректна?) is (Нет)
        -> Да;

        :Ввод размера диагонали смартфона;

        repeat
            :Ввод диагонали смартфона;
            if (Размер корректен?) then (Да)
                
            else (Нет)
                :Вывести сообщение об ошибке;
            endif
        repeat while (Размер корректен?) is (Нет)
        -> Да;
        
        :Приложение отображает сообщение об успешном добавлении смартфона;
    repeat while (Список заполнен до конца?) is (Нет)
    -> Да;

case (3)
    :Завершить программу;
    stop
endswitch

:Сортировать список по убыванию (по сочетанию свойств «модель» и «размер диагонали экрана»);
    :Вывод отсортированного массива;

    if (Сохранить список в файл?) then (Да)
        :Система сохраняет список смартфонов в файл;
    else (Нет)
    endif

repeat while (Выйти из программы?) is (Нет)
-> Да;

stop
@enduml





' @startuml

' ' left to right direction
' ' skinparam packageStyle rectangle

' ' :Пользователь: as user

' ' rectangle "Консольное приложение просмотра телефонов" {
' ' user -- (Отсортировать список\nсмарфонов по убыванию)
' ' (Отсортировать список\nсмарфонов по убыванию) <.. (Сохранить результат в файл) :"extend"
' ' user -- (Добавить смартфоны\nв список)
' ' (Добавление смартфонов\nв список) ..> (Выбор количества смартфонов\nдля внесения в список) :"include"
' ' (Выбор количества смартфонов\nдля внесения в список) ..> (Ввод модели смартфона) : "include"
' ' (Выбор количества смартфонов\nдля внесения в список) ..> (Ввод цены смартфона) :"include"
' ' (Выбор количества смартфонов\nдля внесения в список) ..> (Ввод размера диагонали смартфона) :"include"
' ' }

' @enduml